import os

takes = {
    'anilao': ('Priya', "I stumbled upon Anilao almost by accident \u2014 a friend mentioned the best muck diving within three hours of Manila, and I booked a flight the next week. What I found blew me away: rhinopias, blue-ringed octopus, flamboyant cuttlefish, and more nudibranch species than I could count. The blackwater dives after dark were the standout \u2014 larval fish and planktonic creatures I'd only seen in documentaries. It's not about coral reefs here; it's about the tiny, bizarre, and beautiful. Budget-friendly, too \u2014 you can dive three times a day and still spend under $100."),
    'azores': ('Liam', "While my dive buddies chase tropical reefs, I've been drawn to the Azores for three straight seasons. The Princess Alice Bank delivered my best pelagic encounter anywhere: a dozen mobula rays circling us for twenty minutes, completely unbothered, followed by a blue shark on the safety stop. August water hovers around 22\u00b0C \u2014 chilly but manageable in a 7mm \u2014 and the volcanic seascapes are unlike anything in the Indo-Pacific. The Atlantic swell can cancel dive days without warning, so build buffer into your itinerary. For cold-water pelagic encounters in Europe, nothing touches the Azores."),
    'bali': ('Priya', "Bali is the diver's compromise destination \u2014 my non-diving partner loved the yoga and smoothie bowls while I was underwater with manta rays at Manta Point and hunting for pygmy seahorses in Tulamben. The USAT Liberty wreck is one of the few world-class wrecks accessible from shore \u2014 I did it as a sunrise dive and had the entire site to myself before the crowds arrived. The bumphead parrotfish at Crystal Bay at dawn are hypnotic. For a destination so easy to reach, the diving punches way above its weight. Beginner-friendly yet deeply rewarding for veterans."),
    'belize': ('James', "I'll be honest \u2014 the Blue Hole itself was underwhelming as a dive. Forty-five meters into a dark sinkhole, some stalactites, and not a single fish. But the two reef dives that followed at Lighthouse Reef were unreal: spotted eagle rays in formation, nurse sharks under every ledge, and corals so healthy I forgot I was in the Caribbean. The real star is Turneffe Atoll \u2014 I saw my first Caribbean reef octopus there, changing colors like a living kaleidoscope. Belize is warm, clear, shallow, and where I'd send any newly certified diver for their first tropical trip."),
    'bonaire': ('James', "Shore diving doesn't get better than Bonaire. I rented a pickup truck, loaded tanks in the back, and drove from site to site with a map and zero schedule for an entire week. The Hilma Hooker wreck at 30 meters is the marquee attraction, but the double reef system at Angel City stole the show \u2014 shallow reef, sand channel, deeper wall, all accessible with a giant stride from a parking lot. Bonaire isn't about megafauna; it's about freedom, consistency, and the healthiest Caribbean hard corals I've measured. Eighty-degree water, thirty-meter viz, and no boat schedule to chase."),
    'chuuk-lagoon': ('Aiko', "I've dived wrecks across four continents \u2014 Thistlegorm, Liberty, Zenobia \u2014 but nothing prepared me for Truk Lagoon. Descending onto the San Francisco Maru at 55 meters, still loaded with tanks and munitions from 1944, felt like entering a museum sealed for eighty years. The Fujikawa Maru's engine room, with intact telegraphs and portholes filtering ghostly blue light, is the most atmospheric dive I've ever done. Truk demands experience \u2014 deep wrecks, overhead environments, long deco stops \u2014 but for technical divers, it's the undisputed holy grail of wreck diving."),
    'cocos-island': ('James', "Thirty-six hours each way on a liveaboard for three days of diving. Worth every wave of seasickness. The first time two hundred hammerheads materialized from the blue at Bajo Alcyone, I literally forgot to breathe \u2014 the divemaster tapped my regulator to remind me. Cocos is hammerhead central, but the surprise highlights were the marble rays at night, the tiger sharks at Manuelita, and the Galapagos sharks that followed us like curious puppies on every dive. Negative entries, blue-water ascents, ripping currents. If big animals are your obsession, Cocos delivers like nowhere else in the Eastern Pacific."),
    'cozumel': ('James', "Drift diving at its finest. I barely finned on most dives \u2014 the current just carried me past forty-meter walls draped in orange sponges, through swim-throughs bursting with glassy sweepers, and over sand flats where eagle rays buried themselves for camouflage. Palancar Reef was the standout: towering coral pinnacles, tunnels, and caves that felt designed for divers. My best dive was Santa Rosa Wall at thirty meters, where a spotted eagle ray materialized from the deep blue, soared past inches from my mask, and vanished in seconds. Warm, clear, easy, forty-five minutes from Houston \u2014 the best accessible diving in the Western Hemisphere."),
    'fernando-de-noronha': ('James', "Brazil doesn't get enough credit in the dive world, and Fernando de Noronha proves why it should. Spinner dolphins at morning briefing, sea turtles on every single dive, and the Pedras Secas site where I counted fifteen reef sharks circling below me in one sweeping panorama. The volcanic rock formations create dramatic underwater arches and caverns that feel more Pacific than Atlantic. Visibility isn't Caribbean-perfect \u2014 fifteen to twenty-five meters is typical \u2014 but the sheer biomass more than compensates. Expensive to reach, limited daily permits, no liveaboards. Which is exactly why it's still pristine and uncrowded."),
    'fiji': ('Sofia', "The soft coral capital of the world, and it absolutely lives up to the billing. The Great White Wall in the Somosomo Strait was the most intense color experience of my diving career \u2014 a vertical drop-off completely carpeted in lavender and white soft corals, so dense you couldn't see the rock beneath. Namena Marine Reserve delivered on the big stuff: hammerheads on the north side, barracuda tornadoes in the channel, and a manta cleaning station that worked like clockwork at high tide. Fiji is worth the long flight \u2014 go for at least ten days and split your time between Taveuni and the Bligh Water."),
    'galapagos': ('James', "Darwin and Wolf. Two names every diver should have on their must-dive list. I went in July: eighteen-degree water, green viz, surging current \u2014 but the marine iguana feeding underwater at Cabo Marshall made the cold irrelevant, and the twelve-meter pregnant whale shark at Darwin was the dive of my life. Galapagos is humbling. You are in the ocean's food chain, not above it. Sea lions steal your fins. Hammerheads school by the hundreds. The topography is violent, volcanic, utterly alien. Not for beginners. Not for most advanced divers. For the right diver, nothing on Earth compares."),
    'great-barrier-reef': ('James', "The GBR is so vast it's almost meaningless to say you've dived it. I've done three trips \u2014 Cairns, Port Douglas, and a liveaboard to the Ribbon Reefs \u2014 and each felt like a completely different ocean. Cod Hole delivered massive potato cod that swim right up to your mask. The night dive at Osprey Reef, with oceanic whitetips circling in the boat lights, was pure adrenaline. Inner reef sites near Cairns are fine for beginners but crowded and bleached in places. Skip the day boats. Invest in a three-day liveaboard and get sixty kilometers offshore. That's the Great Barrier Reef you see in documentaries."),
    'kimbe-bay': ('Aiko', "Papua New Guinea is raw, unpredictable, and almost completely untouristed \u2014 exactly why I loved Kimbe Bay. The seamounts here are underwater towers rising from a thousand meters, draped in sea fans and barrel sponges, patrolled by silvertip sharks and massive dogtooth tuna. I had Inglis Shoal to myself on a Tuesday morning, and the resident barracuda school at Christine's Reef must number in the thousands. PNG logistics are challenging \u2014 internal flights, limited infrastructure, variable viz \u2014 but the reward is dive sites you share with maybe four other people. In 2026, that feels almost like a miracle."),
    'komodo': ('Marcus', "Komodo taught me more about drift diving in ten days than the previous hundred dives combined. Batu Bolong at slack tide is an aquarium on steroids \u2014 Napoleon wrasse, turtles, white-tips, and coral so vibrant it looks Photoshopped. Manta Alley at high current delivered twelve mantas barrel-rolling in the cleaning station for forty straight minutes. The secret is timing: dive with operators who read the tides, not the clock. Komodo rewards experience and punishes complacency. Fewer than thirty dives? Wait. Ready for current and negative entries? It's Southeast Asia's best all-around diving, bar none."),
    'lembeh-strait': ('Marcus', "If coral reefs are museums, Lembeh is the library of weird. On a single seventy-minute muck dive at Nudi Falls, I photographed a hairy frogfish, a mimic octopus impersonating a flounder, two Pegasus seamoths mating, and a flamboyant cuttlefish mid-hunt. Zero hard coral. Five-star critter encounters. The black sand slopes look dead from the surface, but within five minutes of descent, your guide will have found something you've never seen before. Lembeh is slow diving \u2014 fin-tip control, ninety-minute bottom times, macro lens mandatory. For lovers of the tiny and bizarre, nowhere else comes close."),
    'malapascua': ('Marcus', "I went for the thresher sharks and stayed for everything else. Monad Shoal at sunrise \u2014 descending to twenty-five meters in the dark, kneeling on the sandy ledge, waiting as the first thresher materializes out of the gloom, tail streaming behind like a silk ribbon \u2014 is a ritual every diver should experience at least once. Five mornings, five sightings. Then Gato Island delivered the most playful cuttlefish I've ever encountered, and the night dive at the lighthouse turned into an hours-long macro treasure hunt. Malapascua is affordable, easy to reach from Cebu, and deserves a spot on every Philippines diving itinerary."),
    'maldives': ('Sofia', "I've done the Maldives both ways \u2014 resort-based day diving and a week-long luxury liveaboard \u2014 and the liveaboard wins by a mile. The channel dives are controlled chaos: hook into the reef at twenty-five meters as grey reef sharks, white-tips, eagle rays, and giant trevally stream past in the current. The night dive at Alimatha Jetty, with thirty-plus nurse sharks and giant stingrays competing for scraps while you kneel in the sand, felt staged but absolutely was not. The Maldives is expensive \u2014 $250 per day minimum on a liveaboard \u2014 but for reliable big-fish encounters in bath-warm water, nothing is more consistent."),
    'palau': ('Sofia', "Blue Corner is famous for a reason. Hook in at fifteen meters as the current rips past the plateau, and within minutes the show starts: grey reef sharks patrolling below, barracuda schools swirling, Napoleon wrasse cruising past at arm's length, turtles so abundant you stop photographing them. I did Blue Corner four times on my week-long trip and each dive was completely different \u2014 one had an oceanic manta parked in the current for thirty minutes. The Jellyfish Lake snorkel between dives is the surreal bonus. Expensive to reach but rewards generously. Minimum fifty dives recommended for the current-heavy signature sites."),
    'poor-knights': ('Aiko', "Subtropical diving off New Zealand's North Island \u2014 no coral at all, but a riot of color from sponges, bryozoans, and anemones in electric orange, pink, and purple. The archways at Northern Arch are cathedral-like, with shafts of light piercing the gloom and short-tail stingrays stacked on the sandy floor like parked cars. I went in February and the water was a brisk twenty degrees in a 7mm suit. The resident school of blue maomao at the namesake arch is mesmerizing \u2014 thousands of fish moving as one organism. Not your tropical postcard, but absolutely unforgettable and worth the journey."),
    'raja-ampat': ('Marcus', "I've logged over 1,200 dives and Raja Ampat is the one place I'd return to every single year if I could. Cape Kri broke my brain \u2014 283 fish species recorded on a single dive is a world record for a reason. Melissa's Garden had hard coral coverage so dense it looked like an aerial photo of a rainforest. The Passage dive, drifting through a mangrove-lined channel with archerfish spitting at insects above and soft coral walls below, is the most unique underwater topography I've ever experienced. Yes, it's remote. Yes, it's expensive. But Raja Ampat is the standard by which all other diving should be measured."),
    'rangiroa': ('Liam', "Tiputa Pass on an incoming tide is the closest I've come to feeling like I'm flying underwater. The current sweeps you through a two-hundred-meter-wide channel at four knots as bottlenose dolphins play in your bubbles and great hammerheads patrol the deep blue below. Visibility is routinely fifty-plus meters in crystal-clear oceanic water. Rangiroa is a single-atoll destination in the Tuamotus, so it's a serious commitment to reach, but the pass dives here are unlike anything in the Caribbean or Indo-Pacific. Best suited to experienced divers comfortable with drift protocols and negative entries into fast current."),
    'red-sea': ('Aiko', "I've dived Egypt's Red Sea three times \u2014 north, central, and Deep South \u2014 and each itinerary is a completely different trip. The Thistlegorm in the north is the world's most famous wreck for a reason: trucks, motorcycles, rifles, and Wellington boots still scattered in the holds eighty years later. Brothers Islands in the central Red Sea delivered oceanic whitetips on every single dive and soft coral walls rivaling Fiji. The Deep South was hammerhead territory \u2014 remote, pristine, and barely dived. The Red Sea is incredible value: a seven-night liveaboard costs what you'd pay for two days in the Maldives."),
    'silfra': ('Liam', "Drinking water while diving is not usually advisable \u2014 but at Silfra, you're swimming through glacial meltwater so pure you can literally drink it mid-dive. The visibility exceeds one hundred meters; I could see divers eighty meters ahead of me as clearly as if they were in an aquarium. The fissure between the North American and Eurasian tectonic plates makes you feel like you're descending through the center of the Earth. At two to four degrees Celsius year-round, a drysuit is non-negotiable, and thirty-five minutes is the max before the cold seeps into your bones. Not about marine life \u2014 there's almost none \u2014 but about geology, clarity, and the sheer weirdness of diving between continents."),
    'similan-islands': ('Sofia', "Richelieu Rock is the best dive site in Thailand, end of debate. A horseshoe-shaped pinnacle in open ocean, covered in purple and pink anemones, with five species of anemonefish defending their territory and whale sharks cruising past if luck is on your side. I did three dives on the Rock during my four-day liveaboard from Khao Lak and each was completely different \u2014 one had a manta ray, one had a massive school of barracuda, one had a zebra shark sleeping peacefully under a coral head. The Similans close May through October for monsoon season, so plan November to April. Liveaboards are the only way to experience the best sites properly."),
    'sipadan': ('Marcus', "Sipadan is a limestone pinnacle rising six hundred meters from the seabed, and the diving is every bit as dramatic as the geology. Barracuda Point at dawn \u2014 descending into a tornado of thousands of chevron barracuda, their silver bodies eclipsing the morning sun \u2014 is the single most iconic dive in Southeast Asia. I counted twenty-three turtles on one dive at Drop-Off, and the whitetip reef sharks at South Point were so numerous I lost count. Daily permits are capped at 120, and they sell out months ahead \u2014 book early. Sipadan is fiercely protected and it shows: the fish biomass here is what every reef should aspire to."),
    'tubbataha': ('Sofia', "Tubbataha is open just three months a year, accessible only by liveaboard, and worth every peso of the planning headache. I went in May as the season was closing, and the water was alive \u2014 whale sharks on the north atoll, tiger sharks cruising the walls, mantas at the cleaning stations on nearly every dive. The reefs are UNESCO-protected, and the coral health is the best I've measured anywhere in the Philippines. No villages, no resorts, no day boats. Just ten liveaboards, forty divers each, and a hundred thousand hectares of pristine ocean. Tubbataha is what the Coral Triangle looked like fifty years ago."),
    'wakatobi': ('Marcus', "Wakatobi is what happens when a resort invests twenty-five years in reef conservation. The house reef alone has more coral diversity than most entire dive destinations \u2014 I logged eighteen dives without leaving the resort's front yard and found new critters on every single one: centuries-old table corals, sea fans the size of small cars, pygmy seahorses in impossible yellow. Wakatobi is luxe: private villas, gourmet meals, and dive guides who know every nudibranch by its Latin name. It's also eye-wateringly expensive at five hundred dollars-plus per day. Not for budget travelers, but for world-class diving with zero compromise on comfort, Wakatobi delivers completely."),
}

base = r'd:\workspace\website\best-places-to-scuba-dive\src\content\destinations'
for slug, (name, take) in takes.items():
    path = os.path.join(base, f'{slug}.yaml')
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    insert = "editorName: '{name}'\neditorTake: |\n  {take}\n".format(name=name, take=take)
    new_content = content.replace(
        'imageCredit: Destination image',
        'imageCredit: Destination image\n' + insert
    )
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)

print(f'Done. Updated {len(takes)} files.')
